#!/usr/bin/env python3
"""Post-process Structurizr's Mermaid export so the diagrams read well in both the
light and dark MkDocs Material themes.

Structurizr's Mermaid exporter bakes in a light-mode look: every file carries a
`linkStyle default fill:#ffffff` line and white `fill:#ffffff` on the outer `diagram`
subgraph and on boundary subgraphs. In Material's dark (slate) theme those render as a
jarring white box with edge-label text stuck on a white patch. The `.mmd` files are
regenerated by `make export`, so this fix lives in the export pipeline rather than as a
hand edit (see docs/maintaining-the-docs.md and ADR 0006).

Transforms applied to each generated/*.mmd (idempotently):
  1. Prepend a Mermaid `%%{init}%%` directive: theme-neutral line/edge-label colors,
     transparent edge-label background (so label text inherits the page color), a font
     stack matching Material, and responsive flowchart sizing.
  2. Drop the `linkStyle default fill:#ffffff` line (links have no fill; line color now
     comes from the init directive's `lineColor`).
  3. Rewrite white `fill:#ffffff`/`stroke:#ffffff` -> `transparent` on `style ...` lines
     only (the diagram wrapper and boundary subgraphs), so the page background shows through
     and the wrapper's white border stops showing as a faint box in dark mode. Black
     deployment-node title text (`color:#000000`, Structurizr's default, invisible on dark)
     is remapped to a neutral gray. Element node fills (indigo/gray/blue/teal/red/brown with
     white text) and colored boundary strokes (e.g. #155fa0) are left untouched.

Usage: postprocess.py [OUT_DIR]   (OUT_DIR defaults to "generated")
"""

import pathlib
import re
import sys

# Single-line Mermaid init directive. Kept on one line so re-running export produces a
# byte-stable first line. `theme: base` lets themeVariables take effect; edgeLabelBackground
# transparent + a mid-gray lineColor read on both light and dark pages.
INIT_DIRECTIVE = (
    "%%{init: {"
    "'theme':'base',"
    "'themeVariables':{"
    "'edgeLabelBackground':'transparent',"
    "'lineColor':'#8b95a1',"
    "'fontFamily':'-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Helvetica,Arial,sans-serif',"
    "'fontSize':'14px'},"
    "'flowchart':{'curve':'basis','useMaxWidth':true}"
    "}}%%"
)

# `fill:#ffffff` on any `style ...`/`linkStyle ...` line (leading whitespace allowed).
_STYLE_LINE = re.compile(r"^(\s*(?:style|linkStyle)\b.*)", re.IGNORECASE)
# The standalone directive Structurizr emits; dropped entirely.
_LINKSTYLE_DEFAULT = re.compile(r"^\s*linkStyle\s+default\s+fill:#ffffff\s*$", re.IGNORECASE)


def process(text: str) -> str:
    lines = text.splitlines()
    out = []

    # 1. Prepend the init directive unless one is already present (idempotent).
    if not (lines and lines[0].lstrip().startswith("%%{init")):
        out.append(INIT_DIRECTIVE)

    for line in lines:
        # 2. Drop Structurizr's meaningless/harmful default link fill.
        if _LINKSTYLE_DEFAULT.match(line):
            continue
        # 3. Neutralize white fills/strokes and black boundary-title text on style lines
        #    only (never element node fills or colored boundary strokes). Black is
        #    Structurizr's default deployment-node title color and is invisible on dark;
        #    a neutral gray reads on both themes.
        if _STYLE_LINE.match(line):
            line = line.replace("fill:#ffffff", "fill:transparent")
            line = line.replace("stroke:#ffffff", "stroke:transparent")
            line = line.replace("color:#000000", "color:#6b7280")
        out.append(line)

    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    out_dir = pathlib.Path(argv[1]) if len(argv) > 1 else pathlib.Path("generated")
    files = sorted(out_dir.glob("*.mmd"))
    if not files:
        print(f"postprocess: no *.mmd files in {out_dir}", file=sys.stderr)
        return 1
    for f in files:
        original = f.read_text(encoding="utf-8")
        updated = process(original)
        if updated != original:
            f.write_text(updated, encoding="utf-8")
    print(f"postprocess: styled {len(files)} Mermaid file(s) in {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
